services:
  data-base:                          #use "data-base" not "localhost"
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  php:
    build: ./php-fpm
    volumes:
      -  ../app:/var/www              #matching the host projetc with the nginx root directory
    depends_on:
      - data-base

  web-service:
    image: nginx
    working_dir: /var/www
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d     #config file location
      - ../app:/var/www               #matching the host projetc with the nginx root directory
    depends_on:
      - php
  


